# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

  api:
    build: ./
    # dockerfile: ./Containerfile
    ports:
      - "8000:8000"
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
    # attachable: true